//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Schema;

namespace Utils.ResourceManager.Factory.Config {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ResProd {
        
        private float intervalField;
        
        private float amountField;
        
        /// <remarks/>
        public float Interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }
        
        /// <remarks/>
        public float Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BuildingConfig : IBuildingConfig {
        
        [XmlAttribute("noNamespaceSchemaLocation", Namespace = XmlSchema.InstanceNamespace)]
        public string namespaceAttribute = "UnitConfig.xsd";
        
        private float strengthField;
        
        private ResProd resProdField;
        
        private float costField;
        
        private string prefabPathField;
        
        /// <remarks/>
        public float Strength {
            get {
                return this.strengthField;
            }
            set {
                this.strengthField = value;
            }
        }

        public float ResProdInterval => ResProd.Interval;
        public float ResProdAmount => ResProd.Amount;

        /// <remarks/>
        public ResProd ResProd {
            get {
                return this.resProdField;
            }
            set {
                this.resProdField = value;
            }
        }
        
        /// <remarks/>
        public float Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        public string PrefabPath {
            get {
                return this.prefabPathField;
            }
            set {
                this.prefabPathField = value;
            }
        }
        
        public override string ToString()
        {
            return $"Strength: {Strength}, ResProdInterval: {ResProdInterval}, ResProdAmount: {ResProdAmount}, " +
                   $"PrefabPath: {PrefabPath}, Cost: {Cost}";
        }
    }
}
